# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_assistant_pb2 as voice__assistant__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceAssistantStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVoice = channel.unary_unary(
                '/voice_assistant.VoiceAssistant/ProcessVoice',
                request_serializer=voice__assistant__pb2.AudioRequest.SerializeToString,
                response_deserializer=voice__assistant__pb2.AudioResponse.FromString,
                _registered_method=True)
        self.StreamVoice = channel.stream_stream(
                '/voice_assistant.VoiceAssistant/StreamVoice',
                request_serializer=voice__assistant__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__assistant__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.GetConversationHistory = channel.unary_unary(
                '/voice_assistant.VoiceAssistant/GetConversationHistory',
                request_serializer=voice__assistant__pb2.HistoryRequest.SerializeToString,
                response_deserializer=voice__assistant__pb2.HistoryResponse.FromString,
                _registered_method=True)


class VoiceAssistantServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamVoice(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversationHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceAssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessVoice,
                    request_deserializer=voice__assistant__pb2.AudioRequest.FromString,
                    response_serializer=voice__assistant__pb2.AudioResponse.SerializeToString,
            ),
            'StreamVoice': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVoice,
                    request_deserializer=voice__assistant__pb2.AudioChunk.FromString,
                    response_serializer=voice__assistant__pb2.AudioChunk.SerializeToString,
            ),
            'GetConversationHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationHistory,
                    request_deserializer=voice__assistant__pb2.HistoryRequest.FromString,
                    response_serializer=voice__assistant__pb2.HistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_assistant.VoiceAssistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_assistant.VoiceAssistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceAssistant(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_assistant.VoiceAssistant/ProcessVoice',
            voice__assistant__pb2.AudioRequest.SerializeToString,
            voice__assistant__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamVoice(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice_assistant.VoiceAssistant/StreamVoice',
            voice__assistant__pb2.AudioChunk.SerializeToString,
            voice__assistant__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversationHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_assistant.VoiceAssistant/GetConversationHistory',
            voice__assistant__pb2.HistoryRequest.SerializeToString,
            voice__assistant__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
